WINDOW_WIDTH, WINDOW_HEIGHT = 1024, 768
BUILD_MAP_SIZE_X, BUILD_MAP_SIZE_Y = 26, 12
BUILD_MAP_SIZE_X_EDGE, BUILD_MAP_SIZE_Y_EDGE = 3, 2
FRAME_MOVE = 8

FRAMEWORK_TYPE_QUIT = -1
FRAMEWORK_TYPE_MAIN = 0
FRAMEWORK_TYPE_BUILD = 1
FRAMEWORK_TYPE_BATTLE = 2
