WINDOW_WIDTH, WINDOW_HEIGHT = 1024, 768
BUILD_MAP_SIZE_X, BUILD_MAP_SIZE_Y = 24, 22
BUILD_MAP_SIZE_X_EDGE, BUILD_MAP_SIZE_Y_EDGE = 6, 8
FRAME_MOVE = 32

FRAMEWORK_TYPE_QUIT = -1
FRAMEWORK_TYPE_MAIN = 0
FRAMEWORK_TYPE_BUILD = 1
FRAMEWORK_TYPE_BATTLE = 2

IMAGE_TYPE_SPRITE = 1
IMAGE_TYPE_FILES = 2
